### ISSUE TITLE
Implement new version of Sketchpane

### ISSUE THREAD

**Issue by setpixel** [wonderunit/storyboarder#1072]
Implement new version of Sketchpane in Storyboarder based on our work on Alchemancy. You can test the online demo here in chrome: https://wonderunit.github.io/alchemancy/

### Tasks

- [x] live stroke alpha
- [x] fix live layer going over layers
- [x] reference layer opacity bug when switching to eraser?
- [x] eraser multi-erase fail?
- [x] tools drawing on wrong layers?
- [x] undo/redo pre-multiply weirdness?
- [x] hook up grain scale in brush shader

Profiling
- [x] Memory use goes up and frame rate goes down during a session of drawing with many strokes. Profile to determine the cause of the memory leaks.

Brush Definitions
- [x] Load from a JSON file
- [x] Reference images in JSON file
- [x] Add Tone
- [x] Re-order brush tools
- [x] Assign key commands to brush tools (1-7). Will need to think about how this changes keymap loading.

File > Exporting
- [x] Export Animated GIF (fails on getCanvasSize) `exporter#exportAnimatedGif`
- [x] Export Scene for Final Cut Pro X
- [x] Export Scene as Images
- [ ] Export to Web
- [x] Export Project as ZIP

File
- [x] Cleanup Scene
- [x] Print to PDF
- [x] Print a Worksheet
- [x] Import Worksheet (fails on getCanvasSize)
- [x] Import Images (fails on getCanvasSize)
- [x] Import Image from mobile server (importImage)

Edit
- [x] Copy
  - [x] Copying a very new board and attempting to paste fails with an `Could not load image` from common#getCanvasImageSourcesDataForBoard
- [x] Paste
  - [x] Reference layer should show default opacity 0.75 when thumbnailing post-paste
  - [x] SketchPane should respect layer opacity when compositing
- [x] Duplicate Board
- [x] Re-ordering Boards
- [x] New Board

Tools
- [x] Flip Horizontal
- [x] Flip Vertical

- [x] Edit in Photoshop (should save to PSD, read PSD on change, update on window refocus)
- [x] Thumbnail does not always update

Help
- [x] Key Commands (need to tie in keys for Quick Erase again?)

Toolbar UI
- [x] Palette Color
  - [x] Loading and Setting from prefs
  - [x] Storing Per-Brush

- [x] Grid Guide
- [x] Center Guide
- [x] Thirds Guide
- [x] 3D Guide
- [x] Onion Skin
  - [x] One below, then layer, then one above
  - [x] Multiply blend mode
  - [x] Test with white backgrounded images
  - [x] Test with multi-scene projects (script-based)

- [x] Captions

Input Modes:
- [x] Move Mode
- [x] Scale Mode
- [x] "Locked" Mode
  - [x] setIsLocked
  - [x] preventIfLocked
  - [x] onDblClick
  - [x] 'requestUnlock' event

- [x] Add White back to color picker

- Sketch Sprint / Pomodoro https://github.com/wonderunit/storyboarder/issues/1125

Timeline
...

Shot Generator
- [x] Drawing to Layer

Layer UI
- [x] Merge Down
- [x] Merge Up
- [x] Layer Opacity Slider
- [x] Layer Clear Button

Drawing
- [x] Line Mileage Counter
- [x] Re-integrate Sound Events (Sonifier)
- [x] Prevent drawing when locked
- [ ] Prevent drawing if pointer is on a UI element above the stage?

SketchPane
- [x] consistent browser cursor setting (currently flashes sometimes)
- [x] hide cursor until first pointer event
- [x] Fix bug where mouse cursor sprite texture is clipped
- [x] layer opacity feature?
- [x] live sketch layer should match opacity of the layer it is drawing on
- [ ] check for memory leaks
  - [ ] PIXI.utils.clearTextureCache()
  - [ ] dispose canvases, textures
  - [ ] https://developers.google.com/web/tools/chrome-devtools/memory-problems/

Misc
- rename grain* in shader (grainMovement, grainScale, grainZoom, etc) for clarity
- [x] test packaging the app. make sure brushes are loading properly
- review uses of getCanvasSize
- review uses of getLayerCanvas, getLayerCanvasByName
- review remaining TODOs added in PR commits

- replace direct references to storyboarderSketchPane.sketchPane with storyboarderSketchPane helper methods
- cleanup copyBoard logic
  - can saveImageFile be sync instead of async?
- review each place where markImageFileDirty([..]) is set manually and determine if it is still necessary

### SketchPane

Review replaceTexture, draw, replace, etc. Try to unify.

We need to set Layer textures from:
- Canvases (for Guides and Onion Skin)
- Images (for reading layer files)
- Display Objects (for internal operations)

replaceTexture destroys the existing texture entirely. Is this really necessary?
Do we ever need to actually destroy and replace the existing texture, or can we
always just render to it? Is there any advantage to replacing the texture vs drawing to it?
How to cleanup after replaceTextureFromCanvas?
Better names for Layer#draw and Layer#replace?
Do we even need Layer#replace?

### CLEANUP
- [x] Remove dead code commented out in PR if it is definitely no longer needed
  - [x] cleanup storyboarder-sketch-pane.js
- [x] Remove old SketchPane classes
- [x] Remove old sketchpane-preview

### FUTURE
- Fix convoluted copy/paste logic (reducers for board, ensure save completes, run async + wait for complete before accepting new commands)
- replace saveDataURLtoFile with utility fn
- [x] onion skin: cancel loading images if we switch away boards
- [x] cache images for re-use (say, a pool of the past 3 or 6 or something?) maybe filestamp/etag checking?

### Related to the Mode Merge

enableBrushCursor
refreshLinkedBoardByFilename
updateSketchPaneBoard
  (replace uses of getLayerCanvasByName)
isCursorOnDrawingArea and window vs container events
  el canvasPointerDown
  sketchPaneDOMElement pointerover
  sketchPaneDOMElement pointerout
    isCursorOnDrawingArea was used for conditional cursor rendering
getCanvasSize
review renderCursor
review onSketchPaneBeforeUp
review onSketchPaneOnUp
add analyticsTiming back / see onFrame

enableDrawingSoundEffects

mergeLayers

insertNewBoardsWithFiles (insertNewBoardsWithFiles)

consistent use of storyboarderSketchPane.replaceLayers. figure out what needs to save undo state and what doesn't. search for uses of layers[n].replace and determine if we should use storyboarderSketchPane.replaceLayers instead

**Comment by df-0** [comment]
Had a play with this (cintiq/osx/chrome), works much much better, pressure sensitivity & eraser work fine, and it's really smooth, much much better for drawing with. Looking forward to this being integrated into storyboarder....

**Comment by christiansass** [comment]
Im loving it

**Comment by audionerd** [comment]
Implemented now in `new-sketchpane` branch. Working to stabilize.
