### ISSUE TITLE
Layers per Tool

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#1115]
Each tool should get its own layer:

Light Pencil > Reference
Brush > Fill
Charcoal > Tone
Pencil > Pencil
Pen > Ink
Notes > Notes

Board data will add an `order` key representing the sort order of the layers. 0 being furthest back away, highest number being in front.
Layers will have names. When we create a layer, we'll give it a name (`name`).
Tools will be associated with default layer names (`defaultLayerName`). If a layer exists with that name, the drawing will happen there.
More than one Tool can be associated with the same Layer name.

In the future, users will be able to assign a layer name (`userLayerName`) to a tool based on the selected layer. If that layer doesn't exist, fallback to the layer with the default layer name.Otherwise Creates layer if it can and doesnt exist, sets correct order. see https://github.com/wonderunit/storyboarder/issues/1161

Two layers can't have the same name. Prevent collisions.

For the initial 2.0 release, layers can't be added or removed. So we can hardcode the naming to start.

If you change the layer name (e.g.: "New Name Here") we update the key e.g.: board-1-uid-new-name-here.png

TODO We'll need to figure out Photoshop import/export

---
### Implementation

- Anywhere we've hardcoded indices (e.g.: [0, 1, 3], or `"// HACK hardcoded"`) will have to change.
- Anywhere we've hardcoded layer constants (e.g.: LAYER_INDEX_*) will have to change
Those should all use name lookups

Have a method to get all user layer names, in order. User layer name do not include system layer names like 'guides' or 'onion'.
Have a method to get the layer index given the layer name.
Have a method to get the layer order given the layer name.

TODO in the future we'll have system layer names vs user facing names, e.g.: 
userName: Crosshatch Pattern
name: crosshatchpattern (all lowercase, ASCII, no spaces)
index: 34
order: 32
extension: crosshatchpattern
Gets saved to board-1-uid-crosshatchpattern.png

SAVING
If a user has never drawn to a layer, it doesn't exist in the board data, and it doesn't exist on the filesystem. Once they draw to a layer, we mark the layer dirty and the board data dirty. When it's time to save, we add the layer to the board layer data (if not present) and save to the file.

NOTE Not backwards compatible. If we save WITHOUT a "main" layer `board.url`, older versions of Storyboarder won't be able to load the board. If this is a problem for users we can write scripts that convert new>old.

Save a full-size "posterframe" JPG for faster preview, pre-loading, and onion skin.

LOADING
For initial 2.0 release, names are hardcoded. So for a new project, we setup all the layers and tools ready to go. When we load a board, we look at its `layers` object to determine what images to load into layers. But the layers all exist regardless.

---
### Migrating older projects

See: #1160

----
### Tasks

- [x] migrating an old board to handle new format for layers
- [x] save
- [x] duplicate
- [x] copy/paste
- [x] onion skin
- [x] insert
- [x] new board
- [x] mergeDown and mergeUp  https://github.com/wonderunit/storyboarder/issues/1172
- [x] exporters
  - [x] Images
  - [x] ZIP
  - [ ] Web
- [x] cleanup scene
- [x] PSD import/export (refreshLinkedBoardByFilename) see https://github.com/wonderunit/storyboarder/issues/1159

---

- [x] updateUrlsFromIndex
