### ISSUE TITLE
Layers

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#154]
# LAYERS

## Main, Reference, and Notes

The app will have three named layers:

- main (the main drawing area)
- reference
- notes

A User can draw on layers using the appropriate tool for that layer:

    Light Pencil  = reference

    Pencil        = main
    Pen           = main
    Brush         = main

    Note Pen      = notes

    Eraser  = operates on all three layers

A User can erase with the Eraser Tool (AKA Fat Eraser) or with another tool in "Quick Erase" mode.

- Eraser Tool (operates on all three layers) #212
- Quick Erase Mode (operates on active layer, toggled via modifier while using active tool, but uses Eraser Tool settings) https://github.com/wonderunit/storyboarder/issues/152

A layer is "active" when its layer tool is active in the toolbar.

## Saving and Loading Layers

Each board will have 1 or more PNG files representing its used layers, e.g.:

    board-1-64C9R.png                 Main Layer (always created)
    board-1-64C9R-reference.png       Reference Layer
    board-1-64C9R-notes.png           Note Pen Layer

When a non-main layer is used (e.g. drawn on at least once in the app), we add it to the `.storyboarder` data:

    {
      "version": "0.3.0",
      "boards": [{
        "url": "board-1-64C9R.png"
        "layers": {
          "reference": {
            "url": "board-1-64C9R-reference.png"
          },
          "notes": {
            "url": "board-1-64C9R-notes.png"
          }
        }
      }]
    }

Each layer is marked dirty individually. Each layer is saved to a file only when drawn on at least once.

---

## Tasks

- [x] Filesystem plan (for naming convention, load/save, etc)
- [x] Ability to load layers
- [x] Ability to save layers
- [x] ability to draw on arbitrary layer of sketchpane
- [x] dirty tracking per-layer
  - [x] only save layers to images if they have been dirtied
  - [x] when saved, update .storyboarder json to reflect the dirtied layer is available for future load/save
  - [x] when loading, try to load based on JSON layer description
- [x] dashes instead of dots in filenames
- [x] include version # in .storyboarder json
- [x] rename drawing to main
- [x] Layer-specific brush tools
- [x] first "next" causes blank screen?
- [x] Test undo/redo drawing with layers

- [x] Layer Operations
- [x] Test undo/redo operations with layers

- [x] Update tooltips for tools to indicate which layer(s) they operate on.

- [x] external image copy/paste works on reference layer

- [x] test with old and new .storyboarders (e.g.: w/o layers key)
- [x] Can load an old .storyboarder w/o layers and everything works

## Layer Operations

- [x] Storing an Undo State:
  - stores the layer on which the operation acted
  - stores the image data

- [x] Undo
  (image data)
    - applies on layer of stored action
    - marks layer dirty
  (board data)
    - ...

- [x] Redo
  (image data)
    - applies on layer of stored action
    - marks layer dirty
  (board data)
    - ...

- [x] New Board
    
- [x] Copy
  - Copy Image Data (copies all visible layers as a flattened image)
  - Copy Board (only existing (aka drawn on) layers layers, new ids)
- [x] Paste
  - Paste Image Data (always external, always to reference layer)
  - Paste Board (new board, paste all existing (aka drawn on) layer image data, saves to layer files)
- [x] Duplicate
  - dupe existing (aka drawn on) layers to new board, new ids, save
- [x] Flip
  - flip ALL layers
- [x] Clear
  - Clear All Layers
  - Clear This Layer (with modifier key)
- [x] Fill
  - Current Layer

---

Future Tasks (found during this work)

- [x] with eraser: first erase works, second erase drawing doesn't do anything :/ pressing alt/option  while drawing confuses eraser tool

- [x] bug: can't undo board delete :/

- [x] replace reference to mainCanvas in main-window

- [x] fix bug where drawing, then creating a new board, copies data onto new board

- [x] "Clear Board" doesn't properly save undo state (i was on eraser)

- [x] Composited Thumbnails #216

- [ ] Layer Move / Scale (see https://github.com/wonderunit/storyboarder/issues/161)
---

## File Changes

```
StoryboardFile (e.g. Scene-1-some-stuff-1-ABC12.storyboarder)
  version // NEW
  aspectRatio: 1.7777777777777777
  fps: 24
  defaultBoardTiming: 2000
  boards

StoryboardBoard
  uid: "64C9R",
  url: "board-1-64C9R.png",
  newShot: false,
  lastEdited: 1492639275392,
  number: 1,
  shot: "1A",
  time: 0,
  lineMileage: 0,
  notes: "Giant drill in spinning idle in the background.",
  dialogue: ""
  layers: // NEW
```
