### ISSUE TITLE
Linked PSDs: changes in Photoshop sometimes don't update in Storyboarder

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#1656]
Many users have noticed Storyboarder does not update from PSD when a linked PSD changes in Photoshop. This has been a problem for a while.

### Dupes
https://github.com/wonderunit/storyboarder/issues/855
https://github.com/wonderunit/storyboarder/issues/963
https://github.com/wonderunit/storyboarder/issues/967
https://github.com/wonderunit/storyboarder/issues/993
https://github.com/wonderunit/storyboarder/issues/1019
https://github.com/wonderunit/storyboarder/issues/1085
https://github.com/wonderunit/storyboarder/issues/1086
https://github.com/wonderunit/storyboarder/issues/1258
https://github.com/wonderunit/storyboarder/issues/1436
https://github.com/wonderunit/storyboarder/issues/1519
https://github.com/wonderunit/storyboarder/issues/1623

### Similar
"Command Failed"
https://github.com/wonderunit/storyboarder/issues/917
"Slow when multiple PSDs linked"
https://github.com/wonderunit/storyboarder/issues/1077

### Tasks

- [x] Read from PSD composite, not layers https://github.com/wonderunit/storyboarder/issues/1654
- [x] Remove the file watcher from `main-window.js` (still used by script watcher in `main.js`)
- [x] Keep a list of "last modified" timestamps for every linked PSD in the project.
- [x] When Storyboarder adds/removes a linked PSD, update the list. (see: `openInEditor`, `requestUnlock`)
- [x] When Storyboarder receives focus, check for active links and see if any of the files timestamps have changed. 
- [x] When switching between boards, do the same timestamp check and update from PSD if necessary
~- [ ] Do we need a slight delay (to avoid issues where the PSD save is still happening in the background). Maybe with a "retry"?~
~- [ ] Can remove the "[...] file that is not linked to any board" check in `refreshLinkedBoardByFilename`~

### To Test

~- [ ] Can we guarantee the focus event won't fire _while we’re already updating?_? If not maybe we need some kind of cancelable generator, so multiple focus changes are fine? (need to test the event coming in during an update)~
- [x] Behavior of re-opening a project with linked PSDs
  - [x] Linking to a PSD, closing Storyboarder, editing the PSD, and re-opening Storyboarder: should re-read from PSD when board is reached and update posterframe and thumbnail. DONE we do this by forcing a read from any linked PSD the first time its board is shown. (Alternately we could have stored the `linkedUpdatedAt` timestamp in JSON)
- [x] Sometimes we get a "Command Failed" from the Photoshop EXE. Can we get a better error message from the command runner?
- [x] When PSD import failed due to unsupported PSD format, need a good error message (should be less frequent now that we're reading from composite, not layers)
- [x] Test loading from a slow disk (network drive maybe?)

**Comment by bobbybutterfly** [comment]
My PSD files are from Clip Studio Paint and i know that these files also make problems when imported in Opentoonz, whereas original PSD files from Photoshop CS 5 will be imported flawlessly

**Comment by audionerd** [comment]
Should be a big improvement when the next version of Storyboarder is released.

Whenever the Storyboarder window is focused, it will check the current board's PSD for changes and update if needed. It doesn't use an independent file watcher anymore.

Storyboarder will read from the single PSD composite image (instead of from each individual PSD layer) which has much better compatibility (for example, text layers and masks will work).

Going to close this issue for now.

But feel free to leave comments here, and let us know if you notice any problems once the release goes out.
