### ISSUE TITLE
Exporters

### ISSUE THREAD

**Issue by setpixel** [wonderunit/storyboarder#37]
export scene script based on boards and info

- [x] export board contact sheet pdf - moved to #351
- [x] export a video - moved to #350 
- [x] export gif
- [x]  ~export xml~ #303 #304
- [x] export scene's boards as flattened images https://github.com/wonderunit/storyboarder/issues/309
- [x] export ordered list to boards in txt - not going to do
- [x] export images in order, and a html player - not going to do

**Comment by setpixel** [comment]
https://github.com/wonderunit/storyboarder/wiki/Final-Cut-XML-Template
