### ISSUE TITLE
Editable key bindings

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#887]
### Overview

Artist can edit a map of commands to keys.
When an artist presses a key, lookup which command is associated, and trigger the command.

The Key Map is stored in keymap.json. Key mapping is 1:1 between command and keystroke. E.g.:

```javascript
{
  "drawing:brush-size:inc": "]",
  "drawing:brush-size:dec": "["
  ...
}
```

TRIGGERS: Keys may trigger a command immediately when pressed (e.g.: ⌘+O to trigger the Open File dialog)

MODAL: Keys may change a behavior only while held (e.g.: holding ⌘ to move art around the 'canvas')

### Notes on the Menu

Some commands can be triggered from the Menu _or_ via keyboard. For example, "Increase Brush Size" can be selected from the Menu (which will send a message via IPC), or it can be triggered via keyboard. But there's a problem:

If a menu item has a `click` event, it will be triggered via mouse select on the menu item, but _also_ when the keys for the `accelerator` are pressed. We can‘t list the `accelerator` shortcut in the menu without also allowing them to trigger the `click` event. The `click` event feels slow, so it's unfortunately we can't bypass it. But we're stuck apparently by the way Electron works.

So: because we want to show `accelerator` keys in the Menu, we have to allow them to route through the `click`.

### Tasks
- [x] Key bindings stored in `keymap.json`. Created if it does not exist. Stored in app data folder.
- [x] Reflect shortcuts in Key Commands window
- [x] Key Command Window should ignore bound key values that aren't supported in its limited keyboard (e.g.: anything not in a simplified QWERTY) and defer to showing those in the "spreadsheet" master view of bindings. Test with AZERTY.

### Not Yet / Future

- User Interface for changing key map
- Watch keymap.json for changes
- Automatically update Menu, Workspace window (Toolbar/Sketchpane/STS) and Key Command window when keymap data changes
- Prevent main window (workspace) from listening to keyboard commands emitted on the Key Command window?

### Known Issues

- Command key on macOS is greedy (see: https://github.com/electron/electron/issues/5188)

### Reference
- `event.key`: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values

The current key commands:
![image](https://user-images.githubusercontent.com/23459/32803906-b2880086-c94a-11e7-8612-14e428b934ae.png)

### Related:
- https://github.com/wonderunit/storyboarder/issues/571
- https://github.com/wonderunit/storyboarder/issues/602
- https://github.com/wonderunit/storyboarder/issues/584
