### ISSUE TITLE
Board audio

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#931]
**Goal: Artists can add one audio file to each board**
To add audio to a board, use the file picker on the sidebar. You can use it directly, or a drag a file to it. In fact, dragging an audio file anywhere on the Storyboarder workspace will attempt to add it to the board.
If the board already has audio associated, artist will be prompted first
Playing from the transport will play audio, picking up partial audio if playing at a midpoint.
MAYBE: Switching between boards via arrow keys can trigger audio as well? Might want to make this an optional thing...

### Tasks

- [x] Each board can have an `audio` object. Saved in JSON. Object is deleted if audio removed
 - [x] `audio` has `filename` if audio present.
- [x] Adding audio files
  - [x] Sidebar Audio file picker
  - [x] Drag and Drop audio file to Workspace
- [x] Adding files should copy them into the project, prepend with correct uid
- [x] Can copy/paste/duplicate boards with audio in them (we make references to the existing audio, not actual copies per board on disk)
- [x] "Clean Up Scene" removes unused files (those not referenced by any `audio` property)
- [x] "Export Project as ZIP" includes audio files
- [x] "Export Scene for Final Cut Pro X and Premiere" warns that audio files will not be included (we'll add that in a later release)
- [x] Playback engine: audio data updated with every change to board data
- [x] Playback engine: knows start/stop/duration for all audio
- [x] Playback engine: start/stop
- [x] Playback engine: synchronization "chasing" - can queue audio to pickup at midpoint
- [x] Icon for audio in board thumbnail
- [x] Detect missing audio files
- [x] Can change scenes and audio loads properly.
- [x] When switching scenes, old audio is cleared out, doesn't remain in memory.
- [x] Clear out unused audio buffers on every updateBuffer call?
- [x] cleanup console.log
- [x] Test Sonifier / Sound Effects, make sure they still work as before
- [x] Check that Tone.js upgrade didn't do anything weird

### Later
- UI toggle for auditioning on/off
- Maybe don't audition first board on load
- Check if loaded, show some kind of notification to user if playback can't happen?

### Assume
- Audio timeline will ignore any timeline change during playback (e.g.: events that are re-arranged during playback)
- Users can't scrub playback
- We won't support decoding in JavaScript at this time, but in the future could add AIFF support with something like `aurora.js`

### Allowed Formats:
- WAV
- MP3
- M4A
- MP4

### Related:
- https://github.com/wonderunit/storyboarder/issues/783
- https://github.com/wonderunit/storyboarder/issues/641
